// "@reduxjs/toolkit": "^1.9.5",
// "@testing-library/jest-dom": "^5.16.5",
// "lord-icon-element": "^4.1.1",
// "react-redux": "^8.0.5",
// "react-spinners": "^0.13.8",
// "styled-components": "^5.3.10",
// "swiper": "^8.4.2",
// "uuid": "^9.0.0",
// "web-vitals": "^2.1.4"
// "test": "react-scripts test",
// "@testing-library/react": "^13.4.0",
// "@testing-library/user-event": "^13.5.0",
// "lottie-web": "^5.11.0",
// "react-select-country-list": "^2.2.3",
// "lottie-web": "^5.11.0",
