const Log_In = "LOG_IN";
const Log_Out = "LOG_OUT";
const Authenticate = "AUTHENTICATE";
const SETACTIVESONG = "SETACTIVESONG";
const NEXTSONG = "NEXTSONG";
const PREVSONG = "PREVSONG";
const PLAYPAUSE = "PLAYPAUSE";
const SELECTGENRELISTID = "SELECGENRELISTID";
const ADDFAVORITEMUSIC = "ADDFAVORITEMUSIC";
const HISTORY = "HISTORY";
const CLEARTHEHISTORY = "CLEARTHEHISTORY";
const REMOVEFAVORITEMUSIC = "REMOVEFAVORITEMUSIC";

export {
  Log_In,
  Log_Out,
  Authenticate,
  SETACTIVESONG,
  NEXTSONG,
  PREVSONG,
  PLAYPAUSE,
  SELECTGENRELISTID,
  ADDFAVORITEMUSIC,
  HISTORY,
  CLEARTHEHISTORY,
  REMOVEFAVORITEMUSIC,
};
